export const TRACK_FILES = [
  "assets/audio/All The Stars.mp3",
  "assets/audio/Anuv Jain - Afsos.mp3",
  "assets/audio/Art of Guitar.mp3",
  "assets/audio/BROWN MUNDE.mp3",
  "assets/audio/Calm Down.mp3",
  "assets/audio/Christina Perri - A Thousand Years.mp3",
  "assets/audio/Co2.mp3",
  "assets/audio/Dil.mp3",
  "assets/audio/Espresso.mp3",
  "assets/audio/greedy.mp3",
  "assets/audio/Happy Nation.mp3",
  "assets/audio/I Wanna Be Yours.mp3",
  "assets/audio/Itna Na Mujhse Tu Pyar Badha.mp3",
  "assets/audio/KEEP UP.mp3",
  "assets/audio/Levitating.mp3",
  "assets/audio/Little Dark Age.mp3",
  "assets/audio/Maand.mp3",
  "assets/audio/Maikada 3.mp3",
  "assets/audio/Midnight City.mp3",
  "assets/audio/Montagem Miau.mp3",
  "assets/audio/Mood.mp3",
  "assets/audio/NOW OR NEVER.mp3",
  "assets/audio/Pal Pal Talwiinder.mp3",
  "assets/audio/Paththavaikkum.mp3",
  "assets/audio/Pink Lips.mp3",
  "assets/audio/Play Date.mp3",
  "assets/audio/Racing Into The Night.mp3",
  "assets/audio/Ransom.mp3",
  "assets/audio/Russian Bandana.mp3",
  "assets/audio/Sahiba.mp3",
  "assets/audio/Something About You.mp3",
  "assets/audio/STFU.mp3",
  "assets/audio/Sush - 2021 Year End Mashup.m4a",
  "assets/audio/Sweater Weather.mp3",
  "assets/audio/São Paulo.mp3",
  "assets/audio/you broke my heart.mp3",
  "assets/audio/Базовый минимум.mp3",
];
